FROM resin/%%RESIN_MACHINE_NAME%%-systemd

MAINTAINER Craig Mulligan <craig@resin.io>

# switch on systemd init system in container


RUN apt-get update && apt-get install -y stress-ng dropbear

# Copy our watchdog configuration, so it can be automatically loaded
RUN echo "RuntimeWatchdogSec=16" >> /etc/systemd/system.conf

# Copy all our source
COPY src /usr/src/app

WORKDIR /usr/src/app

ENTRYPOINT ["bash","entry.sh"]
